from src.controllers.sync_controller import handle_sync_request
from src.controllers.async_controller import handle_async_request
from src.controllers.requests_controller import get_requests, get_request_by_id
